export const CELESTIAL_DATA = {
  sun: {
    id: "sun",
    kind: "star",
    name: "Matahari",
    tagline: "Bintang pusat Tata Surya",
    color: 0xF4B942,
    baseColorHex: "#F4B942",
    diameterKm: 1392700,
    massKg: 1.989e30,
    avgTempC: 5500,
    gravity: 274,
    rotationHours: 609.12,
    photo: "assets/planets/sun.jpg",
    photoCredit: "Sumber: NASA",
    about:
      "Matahari adalah bintang deret utama tipe G yang menyusun lebih dari 99% massa Tata Surya. Energi dari reaksi fusi nuklir di intinya menjadi sumber cahaya dan panas bagi seluruh planet.",
    facts: [
      { label: "Jenis", value: "Bintang katai kuning (tipe G2V)" },
      { label: "Suhu permukaan", value: "≈ 5.500 °C" },
      { label: "Suhu inti", value: "≈ 15.000.000 °C" },
      { label: "Usia", value: "≈ 4,6 miliar tahun" },
    ],
    funFacts: [
      "Cahaya Matahari membutuhkan waktu sekitar 8 menit 20 detik untuk sampai ke Bumi.",
      "Matahari cukup besar untuk memuat lebih dari 1,3 juta planet seukuran Bumi.",
      "Matahari mengorbit pusat galaksi Bima Sakti sekali dalam sekitar 230 juta tahun.",
    ],
  },

  mercury: {
    id: "mercury",
    kind: "planet",
    order: 1,
    name: "Merkurius",
    tagline: "Planet terdekat dengan Matahari",
    color: 0x9C9186,
    baseColorHex: "#9C9186",
    diameterKm: 4879,
    massKg: 3.3011e23,
    avgTempC: 167,
    distanceFromSunKm: 57900000,
    orbitalPeriodDays: 88,
    rotationHours: 1407.6,
    gravity: 3.7,
    moons: 0,
    photo: "assets/planets/mercury.jpg",
    photoCredit: "Sumber: NASA",
    about:
      "Merkurius adalah planet terkecil dan tercepat mengorbit Matahari. Permukaannya dipenuhi kawah seperti Bulan, dengan hampir tanpa atmosfer sehingga suhunya berubah drastis antara siang dan malam.",
    features: [
      "Hampir tidak memiliki atmosfer",
      "Permukaan dipenuhi kawah tumbukan",
      "Tidak memiliki satelit alami",
      "Perbedaan suhu siang-malam paling ekstrem di Tata Surya",
    ],
    funFacts: [
      "Satu hari di Merkurius (matahari terbit ke terbit) setara dengan 176 hari Bumi.",
      "Meskipun paling dekat dengan Matahari, Merkurius bukan planet terpanas — itu adalah Venus.",
      "Terdapat es air di dasar kawah kutub Merkurius yang tidak pernah terkena sinar Matahari.",
    ],
  },

  venus: {
    id: "venus",
    kind: "planet",
    order: 2,
    name: "Venus",
    tagline: "Planet terpanas di Tata Surya",
    color: 0xC9A66B,
    baseColorHex: "#C9A66B",
    diameterKm: 12104,
    massKg: 4.8675e24,
    avgTempC: 464,
    distanceFromSunKm: 108200000,
    orbitalPeriodDays: 224.7,
    rotationHours: -5832.5,
    gravity: 8.87,
    moons: 0,
    photo: "assets/planets/venus.jpg",
    photoCredit: "Sumber: NASA",
    about:
      "Venus memiliki atmosfer sangat tebal yang didominasi karbon dioksida, menciptakan efek rumah kaca ekstrem. Venus berotasi berlawanan arah dibanding kebanyakan planet lain.",
    features: [
      "Atmosfer sangat tebal dan beracun",
      "Efek rumah kaca paling ekstrem",
      "Berotasi retrograde (berlawanan arah)",
      "Permukaan berupa dataran vulkanik luas",
    ],
    funFacts: [
      "Satu hari di Venus lebih lama daripada satu tahunnya.",
      "Tekanan permukaan Venus setara dengan tekanan di kedalaman 900 meter laut Bumi.",
      "Venus adalah objek paling terang di langit malam setelah Bulan.",
    ],
  },

  earth: {
    id: "earth",
    kind: "planet",
    order: 3,
    name: "Bumi",
    tagline: "Rumah bagi kehidupan",
    color: 0x3E7CB1,
    baseColorHex: "#3E7CB1",
    diameterKm: 12742,
    massKg: 5.9724e24,
    avgTempC: 15,
    distanceFromSunKm: 149600000,
    orbitalPeriodDays: 365.25,
    rotationHours: 23.93,
    gravity: 9.81,
    moons: 1,
    photo: "assets/planets/earth.jpg",
    photoCredit: "Sumber: NASA",
    about:
      "Bumi adalah satu-satunya planet yang diketahui memiliki kehidupan. Kombinasi atmosfer pelindung, air cair, dan medan magnet menjadikannya unik di Tata Surya.",
    features: [
      "Memiliki atmosfer kaya oksigen",
      "71% permukaan tertutup air",
      "Satu satelit alami: Bulan",
      "Memiliki medan magnet pelindung",
    ],
    funFacts: [
      "Bumi bukan bola sempurna — sedikit pepat di kutub dan menggembung di khatulistiwa.",
      "Bulan menjauh dari Bumi sekitar 3,8 cm setiap tahun.",
      "Bumi adalah satu-satunya planet yang tidak dinamai menurut dewa Yunani/Romawi.",
    ],
  },

  mars: {
    id: "mars",
    kind: "planet",
    order: 4,
    name: "Mars",
    tagline: "Planet merah",
    color: 0xB1543A,
    baseColorHex: "#B1543A",
    diameterKm: 6779,
    massKg: 6.4171e23,
    avgTempC: -65,
    distanceFromSunKm: 227900000,
    orbitalPeriodDays: 687,
    rotationHours: 24.6,
    gravity: 3.72,
    moons: 2,
    photo: "assets/planets/mars.jpg",
    photoCredit: "Sumber: NASA",
    about:
      "Mars dikenal sebagai planet merah karena oksida besi di permukaannya. Mars memiliki gunung tertinggi dan lembah terbesar di Tata Surya, serta menjadi target utama eksplorasi luar angkasa.",
    features: [
      "Memiliki gunung berapi terbesar: Olympus Mons",
      "Memiliki dua satelit kecil: Phobos dan Deimos",
      "Atmosfer tipis, sebagian besar karbon dioksida",
      "Bukti aliran air purba di masa lalu",
    ],
    funFacts: [
      "Olympus Mons di Mars tingginya sekitar 2,5 kali Gunung Everest.",
      "Satu tahun di Mars hampir sama dengan dua tahun Bumi.",
      "Mars memiliki musim seperti Bumi karena kemiringan sumbunya yang mirip.",
    ],
  },

  jupiter: {
    id: "jupiter",
    kind: "planet",
    order: 5,
    name: "Jupiter",
    tagline: "Planet terbesar di Tata Surya",
    color: 0xC9A97E,
    baseColorHex: "#C9A97E",
    diameterKm: 139820,
    massKg: 1.8982e27,
    avgTempC: -110,
    distanceFromSunKm: 778500000,
    orbitalPeriodDays: 4332.6,
    rotationHours: 9.93,
    gravity: 24.79,
    moons: 95,
    photo: "assets/planets/jupiter.jpg",
    photoCredit: "Sumber: NASA",
    about:
      "Jupiter adalah planet terbesar di Tata Surya, sebuah raksasa gas dengan pola awan berlapis dan badai raksasa yang dikenal sebagai Bintik Merah Besar.",
    features: [
      "Memiliki Bintik Merah Besar, badai raksasa",
      "Cincin tipis yang samar",
      "Puluhan satelit, termasuk empat bulan Galilean",
      "Medan magnet terkuat di antara planet",
    ],
    funFacts: [
      "Bintik Merah Besar di Jupiter cukup besar untuk memuat lebih dari satu Bumi.",
      "Jupiter memiliki hari terpendek di antara semua planet, hanya sekitar 10 jam.",
      "Massa Jupiter lebih besar dari gabungan seluruh planet lain di Tata Surya.",
    ],
  },

  saturn: {
    id: "saturn",
    kind: "planet",
    order: 6,
    name: "Saturnus",
    tagline: "Planet dengan cincin ikonik",
    color: 0xD9C48A,
    baseColorHex: "#D9C48A",
    diameterKm: 116460,
    massKg: 5.6834e26,
    avgTempC: -140,
    distanceFromSunKm: 1434000000,
    orbitalPeriodDays: 10759.2,
    rotationHours: 10.7,
    gravity: 10.44,
    moons: 146,
    hasRings: true,
    photo: "assets/planets/saturn.jpg",
    photoCredit: "Sumber: NASA",
    about:
      "Saturnus terkenal dengan sistem cincinnya yang megah, tersusun dari jutaan partikel es dan batuan. Saturnus adalah raksasa gas dengan kepadatan paling rendah di Tata Surya.",
    features: [
      "Sistem cincin paling menonjol di Tata Surya",
      "Kepadatan lebih rendah dari air",
      "Memiliki lebih dari 140 satelit yang telah dikonfirmasi",
      "Angin atmosfer sangat kencang",
    ],
    funFacts: [
      "Kepadatan Saturnus begitu rendah sehingga secara teori bisa mengapung di air.",
      "Cincin Saturnus sebagian besar tersusun dari es, dengan ketebalan hanya puluhan meter.",
      "Titan, bulan terbesar Saturnus, memiliki atmosfer tebal dan danau metana cair.",
    ],
  },

  uranus: {
    id: "uranus",
    kind: "planet",
    order: 7,
    name: "Uranus",
    tagline: "Planet yang berputar menyamping",
    color: 0x9FD8D0,
    baseColorHex: "#9FD8D0",
    diameterKm: 50724,
    massKg: 8.6810e25,
    avgTempC: -195,
    distanceFromSunKm: 2871000000,
    orbitalPeriodDays: 30687,
    rotationHours: -17.24,
    gravity: 8.69,
    moons: 28,
    hasRings: true,
    photo: "assets/planets/uranus.jpg",
    photoCredit: "Sumber: NASA",
    about:
      "Uranus adalah raksasa es dengan kemiringan sumbu rotasi yang ekstrem, sekitar 98 derajat, sehingga seolah-olah berputar sambil berbaring saat mengorbit Matahari.",
    features: [
      "Sumbu rotasi miring ekstrem (≈98°)",
      "Memiliki sistem cincin tipis",
      "Atmosfer kaya metana yang memberi warna biru-hijau",
      "Berotasi retrograde",
    ],
    funFacts: [
      "Karena kemiringannya, setiap kutub Uranus mengalami sekitar 42 tahun siang terus-menerus.",
      "Uranus adalah planet pertama yang ditemukan menggunakan teleskop, oleh William Herschel pada 1781.",
      "Suhu atmosfer Uranus adalah salah satu yang paling dingin di Tata Surya.",
    ],
  },

  neptune: {
    id: "neptune",
    kind: "planet",
    order: 8,
    name: "Neptunus",
    tagline: "Planet terjauh dan berangin kencang",
    color: 0x4A6FE3,
    baseColorHex: "#4A6FE3",
    diameterKm: 49244,
    massKg: 1.02409e26,
    avgTempC: -200,
    distanceFromSunKm: 4495000000,
    orbitalPeriodDays: 60190,
    rotationHours: 16.11,
    gravity: 11.15,
    moons: 16,
    photo: "assets/planets/neptune.jpg",
    photoCredit: "Sumber: NASA",
    about:
      "Neptunus adalah planet terjauh dari Matahari, sebuah raksasa es berwarna biru cerah dengan angin terkencang yang pernah tercatat di Tata Surya.",
    features: [
      "Angin terkencang di Tata Surya, hingga 2.100 km/jam",
      "Memiliki satelit besar bernama Triton yang mengorbit terbalik",
      "Ditemukan melalui perhitungan matematis sebelum diamati langsung",
      "Warna biru berasal dari metana di atmosfer",
    ],
    funFacts: [
      "Neptunus belum menyelesaikan satu orbit penuh sejak ditemukan tahun 1846 hingga tahun 2011.",
      "Triton, bulan terbesar Neptunus, kemungkinan adalah objek Sabuk Kuiper yang tertangkap gravitasi Neptunus.",
      "Neptunus memancarkan panas internal lebih dari dua kali energi yang diterimanya dari Matahari.",
    ],
  },
};

export const PLANET_ORDER = [
  "mercury",
  "venus",
  "earth",
  "mars",
  "jupiter",
  "saturn",
  "uranus",
  "neptune",
];
